### ISSUE TITLE
GWEN OpenGL 3.x compatible renderer

### ISSUE THREAD

**Issue by dhodvogner** [garrynewman/GWEN#98]
Hello everyone!

I'm started to working on a OpenGL 3.x compatible renderer for GWEN.

~~Sadly i have some issues with the Alpha blending in my shader (maybe.)~~

I think, i found the problem. My shader allways try to use the texture's alpha. 
I'm looking for a good replacement of the Fixed Function Pipeline's gl_disable( GL_TEXTURE_2D)
(Or maybe i have to use two shaders...)

You can found my branch here : https://github.com/dhodvogner/GWEN

I don't have so much time to work on it, so if someone found mistake(s), or have a good/better idea, feel free to contribute :)

**Comment by caseymcc** [comment]
I was able to fix it, your uniform for the texture rendering was always staying on as the call to glGetBooleanv( GL_TEXTURE_2D, &texturesOn ); was always returning texturesOn as 0.

**Comment by dhodvogner** [comment]
Thanks! I'm implemented your fix into my branch too.
